<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Optimizing-Matrix-Operations" data-toc-modified-id="Optimizing-Matrix-Operations-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Optimizing Matrix Operations</a></span><ul class="toc-item"><li><span><a href="#Numpy-with-NumExpr" data-toc-modified-id="Numpy-with-NumExpr-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Numpy with NumExpr</a></span><ul class="toc-item"><li><span><a href="#Evaluation" data-toc-modified-id="Evaluation-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Evaluation</a></span></li><li><span><a href="#Accelerating-loops" data-toc-modified-id="Accelerating-loops-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Accelerating loops</a></span></li><li><span><a href="#Selecting-number-of-threads" data-toc-modified-id="Selecting-number-of-threads-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Selecting number of threads</a></span></li><li><span><a href="#Supported-functions" data-toc-modified-id="Supported-functions-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>Supported functions</a></span></li><li><span><a href="#Supported-reduction-operations" data-toc-modified-id="Supported-reduction-operations-1.1.5"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>Supported reduction operations</a></span></li></ul></li><li><span><a href="#Basic-operations-with-PyTorch" data-toc-modified-id="Basic-operations-with-PyTorch-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Basic operations with PyTorch</a></span><ul class="toc-item"><li><span><a href="#Operations" data-toc-modified-id="Operations-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Operations</a></span><ul class="toc-item"><li><span><a href="#In-place-operation" data-toc-modified-id="In-place-operation-1.2.1.1"><span class="toc-item-num">1.2.1.1&nbsp;&nbsp;</span>In-place operation</a></span></li><li><span><a href="#out" data-toc-modified-id="out-1.2.1.2"><span class="toc-item-num">1.2.1.2&nbsp;&nbsp;</span>out</a></span></li><li><span><a href="#Indexing" data-toc-modified-id="Indexing-1.2.1.3"><span class="toc-item-num">1.2.1.3&nbsp;&nbsp;</span>Indexing</a></span></li><li><span><a href="#Conversion-between-NumPy-ndarray-and-Tensor" data-toc-modified-id="Conversion-between-NumPy-ndarray-and-Tensor-1.2.1.4"><span class="toc-item-num">1.2.1.4&nbsp;&nbsp;</span>Conversion between NumPy ndarray and Tensor</a></span></li><li><span><a href="#Tensor-meta-data" data-toc-modified-id="Tensor-meta-data-1.2.1.5"><span class="toc-item-num">1.2.1.5&nbsp;&nbsp;</span>Tensor meta-data</a></span></li><li><span><a href="#Reshape-Tensor" data-toc-modified-id="Reshape-Tensor-1.2.1.6"><span class="toc-item-num">1.2.1.6&nbsp;&nbsp;</span>Reshape Tensor</a></span></li></ul></li><li><span><a href="#Create-Tensors" data-toc-modified-id="Create-Tensors-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Create Tensors</a></span><ul class="toc-item"><li><span><a href="#Creating-and-Initializing-Tensors" data-toc-modified-id="Creating-and-Initializing-Tensors-1.2.2.1"><span class="toc-item-num">1.2.2.1&nbsp;&nbsp;</span>Creating and Initializing Tensors</a></span></li><li><span><a href="#Creating-random-Tensors" data-toc-modified-id="Creating-random-Tensors-1.2.2.2"><span class="toc-item-num">1.2.2.2&nbsp;&nbsp;</span>Creating random Tensors</a></span></li><li><span><a href="#Tensor-Types" data-toc-modified-id="Tensor-Types-1.2.2.3"><span class="toc-item-num">1.2.2.3&nbsp;&nbsp;</span>Tensor Types</a></span></li><li><span><a href="#Identity-matrices-and-Filled-matrices" data-toc-modified-id="Identity-matrices-and-Filled-matrices-1.2.2.4"><span class="toc-item-num">1.2.2.4&nbsp;&nbsp;</span>Identity matrices and Filled matrices</a></span></li><li><span><a href="#Range-filled-Tensor" data-toc-modified-id="Range-filled-Tensor-1.2.2.5"><span class="toc-item-num">1.2.2.5&nbsp;&nbsp;</span>Range-filled Tensor</a></span></li><li><span><a href="#Log-scale-and-linear-scale-tensors" data-toc-modified-id="Log-scale-and-linear-scale-tensors-1.2.2.6"><span class="toc-item-num">1.2.2.6&nbsp;&nbsp;</span>Log-scale and linear scale tensors</a></span></li><li><span><a href="#ByteTensor" data-toc-modified-id="ByteTensor-1.2.2.7"><span class="toc-item-num">1.2.2.7&nbsp;&nbsp;</span>ByteTensor</a></span></li></ul></li><li><span><a href="#Indexing,-Slicing,-Joining,-Mutating" data-toc-modified-id="Indexing,-Slicing,-Joining,-Mutating-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Indexing, Slicing, Joining, Mutating</a></span><ul class="toc-item"><li><span><a href="#Concatenate,-Stack" data-toc-modified-id="Concatenate,-Stack-1.2.3.1"><span class="toc-item-num">1.2.3.1&nbsp;&nbsp;</span>Concatenate, Stack</a></span></li><li><span><a href="#Gather-(reorganize)-elements" data-toc-modified-id="Gather-(reorganize)-elements-1.2.3.2"><span class="toc-item-num">1.2.3.2&nbsp;&nbsp;</span>Gather (reorganize) elements</a></span></li><li><span><a href="#Split-a-Tensor" data-toc-modified-id="Split-a-Tensor-1.2.3.3"><span class="toc-item-num">1.2.3.3&nbsp;&nbsp;</span>Split a Tensor</a></span></li><li><span><a href="#Index-select-&amp;-Mask-select" data-toc-modified-id="Index-select-&amp;-Mask-select-1.2.3.4"><span class="toc-item-num">1.2.3.4&nbsp;&nbsp;</span>Index select &amp; Mask select</a></span></li><li><span><a href="#Squeeze-&amp;-Unsqueeze" data-toc-modified-id="Squeeze-&amp;-Unsqueeze-1.2.3.5"><span class="toc-item-num">1.2.3.5&nbsp;&nbsp;</span>Squeeze &amp; Unsqueeze</a></span></li><li><span><a href="#Non-zero-elements" data-toc-modified-id="Non-zero-elements-1.2.3.6"><span class="toc-item-num">1.2.3.6&nbsp;&nbsp;</span>Non-zero elements</a></span></li><li><span><a href="#take" data-toc-modified-id="take-1.2.3.7"><span class="toc-item-num">1.2.3.7&nbsp;&nbsp;</span>take</a></span></li><li><span><a href="#transpose" data-toc-modified-id="transpose-1.2.3.8"><span class="toc-item-num">1.2.3.8&nbsp;&nbsp;</span>transpose</a></span></li></ul></li></ul></li><li><span><a href="#Math-with-PyTorch" data-toc-modified-id="Math-with-PyTorch-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Math with PyTorch</a></span><ul class="toc-item"><li><span><a href="#Distributions" data-toc-modified-id="Distributions-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Distributions</a></span><ul class="toc-item"><li><span><a href="#Uniform,-bernoulli,-multinomial,-normal" data-toc-modified-id="Uniform,-bernoulli,-multinomial,-normal-1.3.1.1"><span class="toc-item-num">1.3.1.1&nbsp;&nbsp;</span>Uniform, bernoulli, multinomial, normal</a></span></li><li><span><a href="#Other-Distribution-operations" data-toc-modified-id="Other-Distribution-operations-1.3.1.2"><span class="toc-item-num">1.3.1.2&nbsp;&nbsp;</span>Other Distribution operations</a></span><ul class="toc-item"><li><span><a href="#Random-Sampling" data-toc-modified-id="Random-Sampling-1.3.1.2.1"><span class="toc-item-num">1.3.1.2.1&nbsp;&nbsp;</span>Random Sampling</a></span></li><li><span><a href="#In-place-random-sampling" data-toc-modified-id="In-place-random-sampling-1.3.1.2.2"><span class="toc-item-num">1.3.1.2.2&nbsp;&nbsp;</span>In-place random sampling</a></span></li></ul></li></ul></li><li><span><a href="#Element-wise-operations" data-toc-modified-id="Element-wise-operations-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Element-wise operations</a></span><ul class="toc-item"><li><span><a href="#Add,-subtract,-multiply,-etc.." data-toc-modified-id="Add,-subtract,-multiply,-etc..-1.3.2.1"><span class="toc-item-num">1.3.2.1&nbsp;&nbsp;</span>Add, subtract, multiply, etc..</a></span></li><li><span><a href="#Transcendental-functions-and-other-point-wise-ops" data-toc-modified-id="Transcendental-functions-and-other-point-wise-ops-1.3.2.2"><span class="toc-item-num">1.3.2.2&nbsp;&nbsp;</span>Transcendental functions and other point-wise ops</a></span></li></ul></li><li><span><a href="#Reduction-operations" data-toc-modified-id="Reduction-operations-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Reduction operations</a></span><ul class="toc-item"><li><span><a href="#Cumulative-sum,-mean,-product,-etc.." data-toc-modified-id="Cumulative-sum,-mean,-product,-etc..-1.3.3.1"><span class="toc-item-num">1.3.3.1&nbsp;&nbsp;</span>Cumulative sum, mean, product, etc..</a></span></li><li><span><a href="#Other-reduction-operations" data-toc-modified-id="Other-reduction-operations-1.3.3.2"><span class="toc-item-num">1.3.3.2&nbsp;&nbsp;</span>Other reduction operations</a></span></li></ul></li><li><span><a href="#Comparison-operations" data-toc-modified-id="Comparison-operations-1.3.4"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>Comparison operations</a></span><ul class="toc-item"><li><span><a href="#Equality-and-range" data-toc-modified-id="Equality-and-range-1.3.4.1"><span class="toc-item-num">1.3.4.1&nbsp;&nbsp;</span>Equality and range</a></span></li><li><span><a href="#Sort" data-toc-modified-id="Sort-1.3.4.2"><span class="toc-item-num">1.3.4.2&nbsp;&nbsp;</span>Sort</a></span></li><li><span><a href="#k-th-and-top-k" data-toc-modified-id="k-th-and-top-k-1.3.4.3"><span class="toc-item-num">1.3.4.3&nbsp;&nbsp;</span>k-th and top k</a></span></li><li><span><a href="#Other-comparison-ops" data-toc-modified-id="Other-comparison-ops-1.3.4.4"><span class="toc-item-num">1.3.4.4&nbsp;&nbsp;</span>Other comparison ops</a></span></li></ul></li><li><span><a href="#Matrix,-vector-multiplication" data-toc-modified-id="Matrix,-vector-multiplication-1.3.5"><span class="toc-item-num">1.3.5&nbsp;&nbsp;</span>Matrix, vector multiplication</a></span><ul class="toc-item"><li><span><a href="#Dot-product-of-Tensors" data-toc-modified-id="Dot-product-of-Tensors-1.3.5.1"><span class="toc-item-num">1.3.5.1&nbsp;&nbsp;</span>Dot product of Tensors</a></span></li><li><span><a href="#Matrix-vector-products" data-toc-modified-id="Matrix-vector-products-1.3.5.2"><span class="toc-item-num">1.3.5.2&nbsp;&nbsp;</span>Matrix-vector products</a></span></li><li><span><a href="#Matrix-Matrix-products" data-toc-modified-id="Matrix-Matrix-products-1.3.5.3"><span class="toc-item-num">1.3.5.3&nbsp;&nbsp;</span>Matrix-Matrix products</a></span></li><li><span><a href="#Batch-matrix-multiplication" data-toc-modified-id="Batch-matrix-multiplication-1.3.5.4"><span class="toc-item-num">1.3.5.4&nbsp;&nbsp;</span>Batch matrix multiplication</a></span></li></ul></li><li><span><a href="#Other" data-toc-modified-id="Other-1.3.6"><span class="toc-item-num">1.3.6&nbsp;&nbsp;</span>Other</a></span><ul class="toc-item"><li><span><a href="#Cross-product" data-toc-modified-id="Cross-product-1.3.6.1"><span class="toc-item-num">1.3.6.1&nbsp;&nbsp;</span>Cross product</a></span></li><li><span><a href="#Diagonal-matrices" data-toc-modified-id="Diagonal-matrices-1.3.6.2"><span class="toc-item-num">1.3.6.2&nbsp;&nbsp;</span>Diagonal matrices</a></span></li><li><span><a href="#Histogram" data-toc-modified-id="Histogram-1.3.6.3"><span class="toc-item-num">1.3.6.3&nbsp;&nbsp;</span>Histogram</a></span></li><li><span><a href="#Renormalization" data-toc-modified-id="Renormalization-1.3.6.4"><span class="toc-item-num">1.3.6.4&nbsp;&nbsp;</span>Renormalization</a></span></li><li><span><a href="#Additional-Linear-Algebra-operations" data-toc-modified-id="Additional-Linear-Algebra-operations-1.3.6.5"><span class="toc-item-num">1.3.6.5&nbsp;&nbsp;</span>Additional Linear Algebra operations</a></span></li></ul></li><li><span><a href="#Additional-Operations" data-toc-modified-id="Additional-Operations-1.3.7"><span class="toc-item-num">1.3.7&nbsp;&nbsp;</span>Additional Operations</a></span><ul class="toc-item"><li><span><a href="#Tensors" data-toc-modified-id="Tensors-1.3.7.1"><span class="toc-item-num">1.3.7.1&nbsp;&nbsp;</span>Tensors</a></span></li><li><span><a href="#Serialization" data-toc-modified-id="Serialization-1.3.7.2"><span class="toc-item-num">1.3.7.2&nbsp;&nbsp;</span>Serialization</a></span></li><li><span><a href="#Parallelism" data-toc-modified-id="Parallelism-1.3.7.3"><span class="toc-item-num">1.3.7.3&nbsp;&nbsp;</span>Parallelism</a></span></li><li><span><a href="#Spectral-Ops" data-toc-modified-id="Spectral-Ops-1.3.7.4"><span class="toc-item-num">1.3.7.4&nbsp;&nbsp;</span>Spectral Ops</a></span></li><li><span><a href="#BLAS-and-LAPACK-operations" data-toc-modified-id="BLAS-and-LAPACK-operations-1.3.7.5"><span class="toc-item-num">1.3.7.5&nbsp;&nbsp;</span>BLAS and LAPACK operations</a></span></li></ul></li></ul></li></ul></li></ul></div>

# Optimizing Matrix Operations

## Numpy with NumExpr

The `numexpr` package provides routines for vas *evaluation* of elementwise evaluation of array expressions. It uses a vector-based virtual machine to do so.

__Note that in order to see significant speedup from `numexpr`, arrays need to be around at least 128,000 or so elements.__ With less than this many elements, Numpy may be faster by default.

It is very simple to use:

### Evaluation

In [ ]:
help(ne.evaluate)

In [1]:
import numpy as np
import numexpr as ne

In [24]:
a = np.arange(1000000)
b = np.arange(0, 2000000, 2)

In [28]:
%timeit -n 1000 (2*a+5*b)

7.06 ms ± 88.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [29]:
%timeit -n 1000 ne.evaluate("2*a+5*b")

1.96 ms ± 58.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Accelerating loops

`re_evaluate(local_dict=None)`: Re-evaluate the last array expression without any check. This is meant for accelerating loops that are re-evaluating the same expression repeatedly without

In [41]:
help(ne.re_evaluate)

Help on function re_evaluate in module numexpr.necompiler:

re_evaluate(local_dict=None)
    Re-evaluate the previous executed array expression without any check.
    
    This is meant for accelerating loops that are re-evaluating the same
    expression repeatedly without changing anything else than the operands.
    If unsure, use evaluate() which is safer.
    
    Parameters
    ----------
    
    local_dict : dictionary, optional
        A dictionary that replaces the local operands in current frame.



In [38]:
def my_func1():
    2*a+5*b
    for i in range(10):
        2*a+5*b

def my_func2():
    ne.evaluate("2*a+5*b")
    for i in range(10):
        ne.re_evaluate()
        
def my_func3():
    ne.evaluate("2*a+5*b")
    for i in range(10):
        ne.evaluate("2*a+5*b")
    

In [36]:
%timeit -n 100 my_func1()

77.3 ms ± 1.39 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
%timeit -n 100 my_func2()

21.5 ms ± 205 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [40]:
%timeit -n 100 my_func3()

20.8 ms ± 616 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Selecting number of threads

By default NumExpr automatically detects the number of available logical processing cores and uses as many as it can, up to an initial count of 8. The default maximum that it is able to use is 64.

In [ ]:
help(ne.set_num_threads)

In [30]:
ne.detect_number_of_cores()

8

### Supported functions

 - `where(bool, number1, number2): number` – number1 if the bool condition is true, number2 otherwise.
 - `{sin,cos,tan}(float|complex): float|complex` – trigonometric sine, cosine or tangent.
 - `{arcsin,arccos,arctan}(float|complex): float|complex` – trigonometric inverse sine, cosine or tangent.
 - `arctan2(float1, float2): float` – trigonometric inverse tangent of float1/float2.
 - `{sinh,cosh,tanh}(float|complex): float|complex` – hyperbolic sine, cosine or tangent.
 - `{arcsinh,arccosh,arctanh}(float|complex): float|complex` – hyperbolic inverse sine, cosine or tangent.
 - `{log,log10,log1p}(float|complex): float|complex` – natural, base-10 and log(1+x) logarithms.
 - `{exp,expm1}(float|complex): float|complex` – exponential and exponential minus one.
 - `sqrt(float|complex): float|complex` – square root.
 - `abs(float|complex): float|complex` – absolute value.
 - `conj(complex): complex` – conjugate value.
 - `{real,imag}(complex): float` – real or imaginary part of complex.
 - `complex(float, float): complex` – complex from real and imaginary parts.
 - `contains(str, str): bool` – returns True for every string in `op1` that contains `op2`.

### Supported reduction operations

 - `sum(number, axis=None)`: Sum of array elements over a given axis. Negative axis are not supported.
 - `prod(number, axis=None)`: Product of array elements over a given axis. Negative axis are not supported.

In [65]:
# Adapted from: 
# https://github.com/pydata/numexpr/blob/master/bench/vml_timing2.py

# References:
#
# http://software.intel.com/en-us/intel-mkl
# https://github.com/pydata/numexpr/wiki/NumexprMKL

from __future__ import print_function
import datetime
import sys
import numpy as np
import numexpr as ne
from time import time

N = int(5e7)

x = np.linspace(0, 1, N)
y = np.linspace(0, 1, N)
z = np.empty(N, dtype=np.float64)

# Our working set is 3 vectors of N doubles each
working_set_GB = 3 * N * 8 / 2**30

print("NumPy version: %s" % (np.__version__,))

t0 = time()
z = 2*y + 4*x
t1 = time()
gbs = working_set_GB / (t1-t0)
print("Time for an algebraic expression:     %.3f s / %.3f GB/s" % (t1-t0, gbs))

t0 = time()
z = np.sin(x)**2 + np.cos(y)**2
t1 = time()
gbs = working_set_GB / (t1-t0)
print("Time for a transcendental expression: %.3f s / %.3f GB/s" % (t1-t0, gbs))

#############################################################################

print("\n\n")
ne.use_vml = False

print("Numexpr version: %s. Using MKL: %s" % (ne.__version__, ne.use_vml))

t0 = time()
ne.evaluate('2*y + 4*x', out = z)
t1 = time()
gbs = working_set_GB / (t1-t0)
print("Time for an algebraic expression:     %.3f s / %.3f GB/s" % (t1-t0, gbs))

t0 = time()
ne.evaluate('sin(x)**2 + cos(y)**2', out = z)
t1 = time()
gbs = working_set_GB / (t1-t0)
print("Time for a transcendental expression: %.3f s / %.3f GB/s" % (t1-t0, gbs))

#############################################################################

print("\n\n")
ne.use_vml = True

print("Numexpr version: %s. Using MKL: %s" % (ne.__version__, ne.use_vml))

t0 = time()
ne.evaluate('2*y + 4*x', out = z)
t1 = time()
gbs = working_set_GB / (t1-t0)
print("Time for an algebraic expression:     %.3f s / %.3f GB/s" % (t1-t0, gbs))

t0 = time()
ne.evaluate('sin(x)**2 + cos(y)**2', out = z)
t1 = time()
gbs = working_set_GB / (t1-t0)
print("Time for a transcendental expression: %.3f s / %.3f GB/s" % (t1-t0, gbs))

#############################################################################

print("\n\n")
ne.use_vml = True
ne.set_vml_accuracy_mode('fast')

print("Numexpr version: %s. Using MKL: %s" % (ne.__version__, ne.use_vml))
print("AGGRESSIVE OPTIMIZATION ON and VML ACCURACY = 'fast'")

t0 = time()
ne.evaluate('2*y + 4*x', out = z)#, optimization='aggressive')
t1 = time()
gbs = working_set_GB / (t1-t0)
print("Time for an algebraic expression:     %.3f s / %.3f GB/s" % (t1-t0, gbs))

t0 = time()
ne.evaluate('sin(x)**2 + cos(y)**2', out = z)#, optimization='aggressive')
t1 = time()
gbs = working_set_GB / (t1-t0)
print("Time for a transcendental expression: %.3f s / %.3f GB/s" % (t1-t0, gbs))

#############################################################################

ne.set_vml_accuracy_mode(None)

NumPy version: 1.16.1
Time for an algebraic expression:     1.114 s / 1.003 GB/s
Time for a transcendental expression: 1.745 s / 0.641 GB/s



Numexpr version: 2.6.8. Using MKL: False
Time for an algebraic expression:     0.186 s / 5.998 GB/s
Time for a transcendental expression: 0.146 s / 7.680 GB/s



Numexpr version: 2.6.8. Using MKL: True
Time for an algebraic expression:     0.130 s / 8.581 GB/s
Time for a transcendental expression: 0.165 s / 6.754 GB/s



Numexpr version: 2.6.8. Using MKL: True
AGGRESSIVE OPTIMIZATION ON and VML ACCURACY = 'fast'
Time for an algebraic expression:     0.131 s / 8.537 GB/s
Time for a transcendental expression: 0.140 s / 7.975 GB/s


'fast'

## Basic operations with PyTorch

For the most part, PyTorch is a drop-in replacement for NumPy. Many familiar NumPy functions share the same name in PyTorch, so the API should be very familiar.

The caveat is that PyTorch functions only operate on Tensor-objects, so any non-tensor objects and variables (including NumPy arrays) must be converted to PyTorch tensor objects.

NumPy arrays can be converted to/from Tensor objects very easily, and even share the same memory space as the NumPy objects that they are converted to/from.

In [2]:
import torch

In [3]:
# an un-initialized 2x3 Tensor object, filled with garbage data
x = torch.Tensor(2, 3)
x

tensor([[ 0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [4]:
# a 2x3 Tensor obj initialized with random values between 0 and 1
y = torch.rand(2, 3)
y

tensor([[0.1147, 0.3661, 0.9842],
        [0.1387, 0.4167, 0.3372]])

In [5]:
# equivalent addition operations
z1 = x+y
z2 = torch.add(x, y)

print(z1, z2)

tensor([[0.1147, 0.3661, 0.9842],
        [0.1387, 0.4167, 0.3372]]) tensor([[0.1147, 0.3661, 0.9842],
        [0.1387, 0.4167, 0.3372]])


In [6]:
# take note of what boolean comparison of Tensors returns!
z1==z2

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

### Operations

Fundamental syntax: `torch.is_tensor(obj)`

#### In-place operation

All operations that end with `_` (an underscore) are in-place:

In [7]:
# same as x = x + y
x.add_(y) 

tensor([[0.1147, 0.3661, 0.9842],
        [0.1387, 0.4167, 0.3372]])

In [8]:
x == z1

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

#### out

The result of an operation can be assigned to a variable, therefore all operation methods have an *out* parameter for storing the result:

In [9]:
r1 = torch.Tensor(2, 3)
torch.add(x, y, out=r1)

r2 = torch.add(x, y)

In [10]:
r1 == r2

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

#### Indexing

Exactly the same as Numpy:

In [11]:
# numpy indexing
import numpy as np
a = np.asarray(range(6)).reshape(2,3)
print(a, a[:, 0])

[[0 1 2]
 [3 4 5]] [0 3]


In [125]:
# numpy-like indexing in Pytorch
print(x, x[:, 0])


 7.4906e-01  3.1742e-01  7.3682e-01
 4.4933e-01  1.8515e+28  2.6686e+36
[torch.FloatTensor of size 2x3]
 
 0.7491
 0.4493
[torch.FloatTensor of size 2]



In [126]:
# assignment with indexing
x[:, 0] = 0
x


 0.0000e+00  3.1742e-01  7.3682e-01
 0.0000e+00  1.8515e+28  2.6686e+36
[torch.FloatTensor of size 2x3]

#### Conversion between NumPy ndarray and Tensor

During conversion, both the ndarray and the Tensor will share the same memory. So, changing the NumPy array will also change the Tensor, and visa versa.

In [127]:
# convert
a = np.array([1,2,3,4,5,6])
v = torch.from_numpy(a)     # numpy to tensor

b = v.numpy()    # tensor to numpy

b[1] = -1   # change the tensor

a[1] == b[1]   # show that they are both changed


True

#### Tensor meta-data

In [129]:
x.size()   # the size and dimension of x

torch.Size([2, 3])

In [130]:
torch.numel(x)  # number of elements in x

6

#### Reshape Tensor

In PyTorch, the shape of a Tensor is called the "view":`

In [2]:
import torch
# Re-sizing a tensor
x = torch.randn(2, 3) # size 2x3
y = x.view(6)         # resize to 1x6
z = x.view(-1, 2)     # resize to 3x2, note: does NOT exchange rows and cols

print(x,y,z)


 1.5537 -1.3666 -0.6080
-1.1840 -0.8511 -1.7338
[torch.FloatTensor of size 2x3]
 
 1.5537
-1.3666
-0.6080
-1.1840
-0.8511
-1.7338
[torch.FloatTensor of size 6]
 
 1.5537 -1.3666
-0.6080 -1.1840
-0.8511 -1.7338
[torch.FloatTensor of size 3x2]



### Create Tensors

#### Creating and Initializing Tensors

In [ ]:
v = torch.Tensor(2,3) # A 2x3, un-initialized torch.FloatTensor filled with garbage data
v = torch.Tensor([[1,2],[4,5]]) # 2x2 tensor initalized with specific values
v = torch.LongTensor([1,2,3]) # a Tensor of Long-type data

#### Creating random Tensors

In [3]:
# reproducible results with user-defined random seed
torch.manual_seed(1)

In [24]:
v0 = torch.rand(2, 3)  # uniform distribution
v1 = torch.randn(2, 3) # normal distribution (SD=1, mean=0)
v2 = torch.randperm(4) # random permutation of integers from 0 to 4

print(v0,v1,v2)


 0.5159  0.1541  0.8908
 0.3750  0.4596  0.0693
[torch.FloatTensor of size 2x3]
 
 0.3742  1.4532  1.4057
-1.2860 -0.6946  0.1770
[torch.FloatTensor of size 2x3]
 
 2
 1
 3
 0
[torch.LongTensor of size 4]



#### Tensor Types

In [29]:
v0 = torch.randn(5, 3).type(torch.FloatTensor)
v1 = torch.randn(5, 3).type(torch.DoubleTensor)
print(v0, v1)


-0.2330  0.6424  0.0899
 1.4849  0.0087 -0.4798
 0.9808  0.2786  1.6559
 0.3677  2.5169  0.1226
-0.3431 -0.8052 -0.8996
[torch.FloatTensor of size 5x3]
 
-0.1665 -1.2544  0.4524
-1.8438 -0.6672  1.3412
-0.6061 -1.3228  0.5589
-0.0543  0.5147  0.3752
 0.4385 -0.9105 -0.8118
[torch.DoubleTensor of size 5x3]



#### Identity matrices and Filled matrices

In [31]:
I = torch.eye(3)  # 3x3 identity matrix

v0 = torch.ones(10)
v1 = torch.ones(2,1,2,1)
v2 = torch.ones_like(I)

v3 = torch.zeros(10)

v4 = torch.ones(3, 3)
v4[1].fill_(2)
v4[2].fill_(3)

print(I, v0, v1, v2, v3, v4)


 1  0  0
 0  1  0
 0  0  1
[torch.FloatTensor of size 3x3]
 
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
[torch.FloatTensor of size 10]
 
(0 ,0 ,.,.) = 
  1
  1

(1 ,0 ,.,.) = 
  1
  1
[torch.FloatTensor of size 2x1x2x1]
 
 1  1  1
 1  1  1
 1  1  1
[torch.FloatTensor of size 3x3]
 
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
[torch.FloatTensor of size 10]
 
 1  1  1
 2  2  2
 3  3  3
[torch.FloatTensor of size 3x3]



#### Range-filled Tensor

In [36]:
# similar to range, same API as np.arange
v0 = torch.arange(5)
v1 = torch.arange(0, 5, step=1)

v2 = torch.arange(9).view(3,3)

print(v0,v1,v2)


 0
 1
 2
 3
 4
[torch.FloatTensor of size 5]
 
 0
 1
 2
 3
 4
[torch.FloatTensor of size 5]
 
 0  1  2
 3  4  5
 6  7  8
[torch.FloatTensor of size 3x3]



#### Log-scale and linear scale tensors

In [37]:
v0 = torch.linspace(1,10, steps=10)
v1 = torch.logspace(start=-10, end=10, steps=5)

print(v0, v1)


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
[torch.FloatTensor of size 10]
 
 1.0000e-10
 1.0000e-05
 1.0000e+00
 1.0000e+05
 1.0000e+10
[torch.FloatTensor of size 5]



#### ByteTensor

In [38]:
c = torch.ByteTensor([0,1,1,0])
c


 0
 1
 1
 0
[torch.ByteTensor of size 4]

### Indexing, Slicing, Joining, Mutating

In [133]:
# prepare a Matrix for use in this section

v = torch.arange(9).view(3,3)
v


 0  1  2
 3  4  5
 6  7  8
[torch.FloatTensor of size 3x3]

#### Concatenate, Stack

In [135]:
torch.cat((v,v,v), 0) #concat in the 0th dimension


    0     1     2
    3     4     5
    6     7     8
    0     1     2
    3     4     5
    6     7     8
    0     1     2
    3     4     5
    6     7     8
[torch.FloatTensor of size 9x3]

In [136]:
torch.cat((v,v,v), 1) #concat in the 1st dimension


    0     1     2     0     1     2     0     1     2
    3     4     5     3     4     5     3     4     5
    6     7     8     6     7     8     6     7     8
[torch.FloatTensor of size 3x9]

#### Gather (reorganize) elements

In [142]:
# Syntax:
# torch.gather(input, dim, index, out=None)

r = torch.gather(v, 1, torch.LongTensor([[0,2],[0,1],[1,2]]))
r


 0  2
 3  4
 7  8
[torch.FloatTensor of size 3x2]

#### Split a Tensor

In [144]:
# split into 3 chunks
torch.chunk(v, 3)

(
  0  1  2
 [torch.FloatTensor of size 1x3], 
  3  4  5
 [torch.FloatTensor of size 1x3], 
  6  7  8
 [torch.FloatTensor of size 1x3])

In [146]:
# split into chunks of size 2 (or less)
torch.split(v, 2)

(
  0  1  2
  3  4  5
 [torch.FloatTensor of size 2x3], 
  6  7  8
 [torch.FloatTensor of size 1x3])

#### Index select & Mask select

In [148]:
# index-based select
indices = torch.LongTensor([0,2])
r = torch.index_select(v, 1, indices)
print(v, r)


 0  1  2
 3  4  5
 6  7  8
[torch.FloatTensor of size 3x3]
 
 0  2
 3  5
 6  8
[torch.FloatTensor of size 3x2]



In [153]:
# mask select
mask = v.ge(4) # create a mask, slecting all elements >= 4
r = torch.masked_select(v, mask)
print(mask, v, r)


 0  0  0
 0  1  1
 1  1  1
[torch.ByteTensor of size 3x3]
 
 0  1  2
 3  4  5
 6  7  8
[torch.FloatTensor of size 3x3]
 
 4
 5
 6
 7
 8
[torch.FloatTensor of size 5]



#### Squeeze & Unsqueeze

In [39]:
#squeeze
t = torch.ones(2,1,2,1)
r0 = torch.squeeze(t) #squeeze into a 2x2
r1 = torch.squeeze(t, 1) # squeeze dimension one

print(t, r0, r1)


(0 ,0 ,.,.) = 
  1
  1

(1 ,0 ,.,.) = 
  1
  1
[torch.FloatTensor of size 2x1x2x1]
 
 1  1
 1  1
[torch.FloatTensor of size 2x2]
 
(0 ,.,.) = 
  1
  1

(1 ,.,.) = 
  1
  1
[torch.FloatTensor of size 2x2x1]



In [41]:
#un-squeeze
x = torch.Tensor([1,2,3])
r0 = torch.unsqueeze(x, 0)
r1 = torch.unsqueeze(x, 1)

print(x, r0, r1)


 1
 2
 3
[torch.FloatTensor of size 3]
 
 1  2  3
[torch.FloatTensor of size 1x3]
 
 1
 2
 3
[torch.FloatTensor of size 3x1]



#### Non-zero elements

Selection index for all on-zero elements.

In [43]:
v = torch.LongTensor([[1, 0],
                      [0, 2],
                      [2, 3],
                      [2, 0],
                      [0, 0],
                      [1, 2]])

r = torch.nonzero(v) # returns the [i, j] indices for all non-zero elements
print(r)


    0     0
    1     1
    2     0
    2     1
    3     0
    5     0
    5     1
[torch.LongTensor of size 7x2]

#### take

In [46]:
# Flatten a Tensor and return elements with the given indices
v = torch.LongTensor([[1, 0, 3],
                      [7, 9, 1]])

r = torch.take(v, torch.LongTensor([0, 2, 4, -1]))
print(r)


 1
 3
 9
 1
[torch.LongTensor of size 4]



#### transpose

In [47]:
# transpose dimensions 0 and 1
torch.transpose(v, 0, 1)


 1  7
 0  9
 3  1
[torch.LongTensor of size 3x2]

## Math with PyTorch

### Distributions

#### Uniform, bernoulli, multinomial, normal

In [50]:
# 2x2 uniformly distributed random matrix, range [0, 1]
r0 = torch.Tensor(2, 2).uniform_(0,1)

# bernoulli
r1 = torch.bernoulli(r0)

# multinomial
w = torch.Tensor([0,4,8,2]) # Create a tensor of weights
r2 = torch.multinomial(w, 4, replacement=True) # size 4

# normal distribution
# size 10
r3 = torch.normal(means=torch.arange(1,11), std=torch.arange(1, 0.1, -0.1))

print(r0,r1,r2,r3)


 0.8860  0.3710
 0.1769  0.8206
[torch.FloatTensor of size 2x2]
 
 1  1
 0  1
[torch.FloatTensor of size 2x2]
 
 3
 1
 2
 3
[torch.LongTensor of size 4]
 
 1.5864
 2.0861
 4.1725
 3.4981
 4.6949
 6.6555
 6.2695
 8.0898
 8.7139
 9.9370
[torch.FloatTensor of size 10]



#### Other Distribution operations

##### Random Sampling
```
.. autofunction:: manual_seed    - Set a manual seed
.. autofunction:: initial_seed   - Randomize a seed by the system
.. autofunction:: get_rng_state
.. autofunction:: set_rng_state
.. autodata:: default_generator
.. autofunction:: bernoulli
.. autofunction:: multinomial
.. autofunction:: normal
.. autofunction:: rand
.. autofunction:: randn
.. autofunction:: randperm
```

##### In-place random sampling
```
- torch.Tensor.bernoulli_ - in-place version of :func:`torch.bernoulli`
- torch.Tensor.cauchy_ - numbers drawn from the Cauchy distribution
- torch.Tensor.exponential_ - numbers drawn from the exponential distribution
- torch.Tensor.geometric_ - elements drawn from the geometric distribution
- torch.Tensor.log_normal_ - samples from the log-normal distribution
- torch.Tensor.normal_ - in-place version of :func:`torch.normal`
- torch.Tensor.random_ - numbers sampled from the discrete uniform distribution
- torch.Tensor.uniform_ - numbers sampled from the continuous uniform distribution
```

### Element-wise operations

#### Add, subtract, multiply, etc..

In [53]:
# absolute value
f = torch.FloatTensor([-1,-2,3])
r0 = torch.abs(f)

# addition
x = torch.FloatTensor([-1, -2, 3])
y = torch.FloatTensor([7, 4, -5])
r1 = torch.add(x, 10) # add scalar 10 to x
r2 = torch.add(x, 10, y) # sum of x, y, and scalar 10

# clamp the value of a tensor
v = torch.Tensor(2, 2).uniform_(0,1)
r3 = torch.clamp(v, min=-0.5, max=0.5)

# element-wise division
r4 = torch.div(v, v+0.1)

# element-wise multiplication
r5 = torch.mul(v, v)

print(r0,r1,r2,r3,r4,r5)


 1
 2
 3
[torch.FloatTensor of size 3]
 
  9
  8
 13
[torch.FloatTensor of size 3]
 
 69
 38
-47
[torch.FloatTensor of size 3]
 
 0.4495  0.2544
 0.5000  0.5000
[torch.FloatTensor of size 2x2]
 
 0.8180  0.7179
 0.8362  0.8655
[torch.FloatTensor of size 2x2]
 
 0.2021  0.0647
 0.2605  0.4142
[torch.FloatTensor of size 2x2]



#### Transcendental functions and other point-wise ops

```
.. autofunction:: abs
.. autofunction:: acos           - arc cosine
.. autofunction:: add
.. autofunction:: addcdiv        - element wise: t1 + s * t2/t3
.. autofunction:: addcmul        - element wise: t1 + s * t2 * t3
.. autofunction:: asin           - arc sin
.. autofunction:: atan
.. autofunction:: atan2
.. autofunction:: ceil           - ceiling
.. autofunction:: clamp          - clamp elements into a range
.. autofunction:: cos
.. autofunction:: cosh
.. autofunction:: div            - divide
.. autofunction:: erf            - Gaussian error functiom
.. autofunction:: erfinv         - Inverse
.. autofunction:: exp
.. autofunction:: expm1          - exponential of each element minus 1
.. autofunction:: floor          
.. autofunction:: fmod           - element wise remainder of division
.. autofunction:: frac           - fraction part 3.4 -> 0.4
.. autofunction:: lerp           - linear interpolation
.. autofunction:: log            - natural log
.. autofunction:: log1p          - y = log(1 + x)
.. autofunction:: mul            - multiple
.. autofunction:: neg 
.. autofunction:: pow
.. autofunction:: reciprocal     - 1/x
.. autofunction:: remainder      - remainder of division
.. autofunction:: round
.. autofunction:: rsqrt          - the reciprocal of the square-root 
.. autofunction:: sigmoid        - sigmode(x)
.. autofunction:: sign
.. autofunction:: sin
.. autofunction:: sinh
.. autofunction:: sqrt
.. autofunction:: tan
.. autofunction:: tanh
.. autofunction:: trunc          - truncated integer
```

### Reduction operations

#### Cumulative sum, mean, product, etc.. 

In [69]:
# Cumulative sum
v = torch.ones(9)
r0 = torch.cumsum(v, dim=0).view(3,3)

# Mean
r1 = torch.mean(r0.view(9), dim=0)

# Sum
r2 = torch.sum(r0, dim=1)
r3 = torch.sum(r0)

print(r0,r1,r2,r3)


 1  2  3
 4  5  6
 7  8  9
[torch.FloatTensor of size 3x3]
 
 5
[torch.FloatTensor of size 1]
 
  6
 15
 24
[torch.FloatTensor of size 3]
 45.0


#### Other reduction operations

```
.. autofunction:: cumprod        - accumulate product of elements x1*x2*x3...
.. autofunction:: cumsum
.. autofunction:: dist           - L-p norm
.. autofunction:: mean
.. autofunction:: median
.. autofunction:: mode
.. autofunction:: norm           - L-p norm
.. autofunction:: prod           - accumulate product
.. autofunction:: std            - compute standard deviation
.. autofunction:: sum
.. autofunction:: var            - variance of all elem
```

### Comparison operations

#### Equality and range

In [82]:
v = torch.arange(9).view(3,3)

# element-wise comparison
r0 = torch.eq(v, v)

# max element
r1 = torch.max(v) # max element in whole tensor
r2 = torch.max(v, 1) # max element in dimension 1

print("v = ", v, "\n\n r0 = ", r0, "\n\n r1 = ", r1, "\n\n r2 = ", r2)

v =  
 0  1  2
 3  4  5
 6  7  8
[torch.FloatTensor of size 3x3]
 

 r0 =  
 1  1  1
 1  1  1
 1  1  1
[torch.ByteTensor of size 3x3]
 

 r1 =  8.0 

 r2 =  (
 2
 5
 8
[torch.FloatTensor of size 3]
, 
 2
 2
 2
[torch.LongTensor of size 3]
)


#### Sort

In [89]:
v = torch.randn(9).view(3,3)
r0 = torch.sort(v)
r1 = torch.sort(v, 0)
r2 = torch.sort(v.view(9))

print(r0, r1, r2) # note that the second tuple of each output is the index

(
-1.2034 -0.9490  0.3767
-1.5232 -0.5664 -0.5357
-0.6016  0.4215  1.7833
[torch.FloatTensor of size 3x3]
, 
 0  1  2
 0  1  2
 1  2  0
[torch.LongTensor of size 3x3]
) (
-1.5232 -0.9490 -0.5357
-1.2034 -0.6016  0.3767
 1.7833 -0.5664  0.4215
[torch.FloatTensor of size 3x3]
, 
 1  0  1
 0  2  0
 2  1  2
[torch.LongTensor of size 3x3]
) (
-1.5232
-1.2034
-0.9490
-0.6016
-0.5664
-0.5357
 0.3767
 0.4215
 1.7833
[torch.FloatTensor of size 9]
, 
 3
 0
 1
 7
 4
 5
 2
 8
 6
[torch.LongTensor of size 9]
)


#### k-th and top k

In [97]:
v_sorted = torch.sort(v.view(1,9))[0]
r0 = torch.kthvalue(v_sorted, 4)

print(v_sorted, r0)


-1.5232 -1.2034 -0.9490 -0.6016 -0.5664 -0.5357  0.3767  0.4215  1.7833
[torch.FloatTensor of size 1x9]
 (
-0.6016
[torch.FloatTensor of size 1]
, 
 3
[torch.LongTensor of size 1]
)


In [100]:
r0 = torch.topk(v_sorted, 1)
print(r0)

(
 1.7833
[torch.FloatTensor of size 1x1]
, 
 8
[torch.LongTensor of size 1x1]
)


#### Other comparison ops

```
.. autofunction:: eq             - Compare elements
.. autofunction:: equal          - True of 2 tensors are the same 
.. autofunction:: ge             - Element-wise greater or equal comparison
.. autofunction:: gt
.. autofunction:: kthvalue       - k-th element
.. autofunction:: le
.. autofunction:: lt
.. autofunction:: max
.. autofunction:: min
.. autofunction:: ne
.. autofunction:: sort
.. autofunction:: topk           - top k
```

### Matrix, vector multiplication

#### Dot product of Tensors

In [103]:
# Dot product of 2 tensors
a = torch.Tensor([4, 2])
b = torch.Tensor([3, 1])
r = torch.dot(a, b)

r

14.0

#### Matrix-vector products

In [109]:
# Matrix times vector
A = torch.randn(2, 4)
x = torch.randn(4)
r0 = torch.mv(A, x)

# Matrix + Matrix times vector
B = torch.randn(2)
A = torch.randn(2, 3)
x = torch.randn(3)
r1 = torch.addmv(B, A, x)

print(r0, r1)


 2.6792
-2.3246
[torch.FloatTensor of size 2]
 
-0.3820
-4.1244
[torch.FloatTensor of size 2]



####  Matrix-Matrix products

In [110]:
# Matrix times Matrix
m1 = torch.randn(2, 3)
m2 = torch.randn(3, 4)
r0 = torch.mm(m1, m2)

# Matrix + Matrix times Matrix
# Size 3x4
M = torch.randn(3, 4)
m1 = torch.randn(3, 2)
m2 = torch.randn(2, 4)
r1 = torch.addmm(M, m1, m2)

print(r0, r1)


-1.2783  1.6427 -1.4557  0.9254
-0.4794  1.6348 -2.9228  0.0080
[torch.FloatTensor of size 2x4]
 
 0.5492 -1.1988 -0.2204  0.5866
 4.1753 -3.2758  3.9218  0.6591
 1.1895 -0.7514  0.6088  1.8811
[torch.FloatTensor of size 3x4]



#### Batch matrix multiplication

In [111]:
# Batch Matrix x Matrix
# Size 10x3x5
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
r = torch.bmm(batch1, batch2)

r


(0 ,.,.) = 
  1.2020  1.6921 -1.1332  1.0529  0.6079
 -0.6649 -0.4825  1.8081 -0.4529  1.4641
 -1.6707 -0.5038  1.3220 -0.2272  0.4810

(1 ,.,.) = 
  1.0112  1.1443  0.7109 -0.7624  2.0415
  0.4586  1.1151 -2.5277  1.5978  0.2435
  0.7323 -0.5396  3.3860 -1.8553  1.8893

(2 ,.,.) = 
 -0.4275  1.2501 -1.2290 -0.9170  1.8273
 -0.6443  0.3324  0.6728  0.0685  0.5815
 -2.4623 -2.6342  2.0456 -2.7469 -1.0342

(3 ,.,.) = 
 -3.4735 -3.2363 -0.1630 -3.6588  1.4984
  0.0211  0.3152  0.5639 -0.2571  0.0268
 -0.5573  1.4446  1.2297  0.8977  1.9769

(4 ,.,.) = 
 -1.7322  0.0131 -0.3421  0.3138  0.6157
 -2.0619 -1.4659  0.5456 -2.5309 -1.6549
  3.8718  2.2077  0.3109  0.2547 -0.3231

(5 ,.,.) = 
  1.4676 -4.6733 -4.1246 -0.7250 -1.4464
  1.4983 -4.2356 -2.6123 -1.4424 -4.5579
 -9.2738  6.6039  1.2784 -4.7086  1.7607

(6 ,.,.) = 
 -0.0644  2.5195 -2.3923 -0.7669 -2.7215
  3.6016 -3.5442  5.0215  1.8794  1.5366
 -2.4428  3.2052 -3.9410 -1.3501 -1.8186

(7 ,.,.) = 
 -0.7680 -0.0047  0.3483  0.1806  0

### Other

#### Cross product

In [112]:
m1 = torch.ones(3, 5)
m2 = torch.ones(3, 5)
v1 = torch.ones(3)

# Cross product, 3x5
r = torch.cross(m1, m2)

r


 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
[torch.FloatTensor of size 3x5]

#### Diagonal matrices

In [114]:
# Diagonal matrix, 3x3
r = torch.diag(v1)
r


 1  0  0
 0  1  0
 0  0  1
[torch.FloatTensor of size 3x3]

#### Histogram

In [115]:
torch.histc(torch.FloatTensor([1, 2, 1]), bins=4, min=0, max=3)


 0
 2
 1
 0
[torch.FloatTensor of size 4]

#### Renormalization

In [117]:
# Renormalize
# Renormalize for L-1 at dim 0 with max of 1
# 0.0000  0.3333  0.6667
# 0.2500  0.3333  0.4167
# 0.2857  0.3333  0.3810
r = torch.renorm(v, 1, 0, 1)

print(v, r)


-1.2034 -0.9490  0.3767
-1.5232 -0.5664 -0.5357
 1.7833 -0.6016  0.4215
[torch.FloatTensor of size 3x3]
 
-0.4758 -0.3752  0.1489
-0.5802 -0.2157 -0.2040
 0.6354 -0.2144  0.1502
[torch.FloatTensor of size 3x3]



#### Additional Linear Algebra operations

```
.. autofunction:: cross           - cross product
.. autofunction:: diag            - convert vector to diagonal matrix
.. autofunction:: histc           - histogram
.. autofunction:: renorm          - renormalize a tensor
.. autofunction:: trace           - tr(M)
.. autofunction:: tril            - lower triangle of 2-D matrix 
.. autofunction:: triu            - uppser triangle
```

### Additional Operations

#### Tensors

```
.. autofunction:: is_tensor
.. autofunction:: is_storage
.. autofunction:: set_default_tensor_type
.. autofunction:: numel
.. autofunction:: set_printoptions
```

#### Serialization

```
.. autofunction:: save          - Saves an object to a disk file
.. autofunction:: load          - Loads an object saved with torch.save() from a file
```

#### Parallelism

```
.. autofunction:: get_num_threads - Gets the number of OpenMP threads used for parallelizing CPU operations
.. autofunction:: set_num_threads
```

#### Spectral Ops

```
.. autofunction:: stft          - Short-time Fourier transform 
.. autofunction:: hann_window   - Hann window function
.. autofunction:: hamming_window  - Hamming window function
.. autofunction:: bartlett_window - Bartlett window function
```

#### BLAS and LAPACK operations

```
.. autofunction:: addbmm          - Batch add and mulitply matrices nxp + b×n×m X b×m×p -> bxnxp
.. autofunction:: addmm           - Add and mulitply matrices nxp + n×m X m×p -> nxp
.. autofunction:: addmv           - Add and matrix, vector multipy n + nxm X m -> n
.. autofunction:: addr            - Outer product of vectors
.. autofunction:: baddbmm         - Batch add and mulitply matrices
.. autofunction:: bmm             - Batch mulitply matrices b×n×m X b×m×p -> b×n×p
.. autofunction:: btrifact        - LU factorization
.. autofunction:: btrifact_with_info
.. autofunction:: btrisolve
.. autofunction:: btriunpack
.. autofunction:: dot             - Dot product of 2 tensors
.. autofunction:: eig             - Eigenvalues and eigenvectors ofsquare matrix
.. autofunction:: gels            - Solution for least square or p-norm(AX - B)
.. autofunction:: geqrf
.. autofunction:: ger             - Outer product of 2 vectors
.. autofunction:: gesv            - Solve linear equations
.. autofunction:: inverse         - Inverse of square matrix
.. autofunction:: det             - Determinant of a 2D square Variable
.. autofunction:: matmul          - Matrix product of tensors
.. autofunction:: mm				- Matrix multiplication
.. autofunction:: mv              - Matrix vector product
.. autofunction:: orgqr           - Orthogal matrix Q 
.. autofunction:: ormqr           - Multiplies matrix by the orthogonal Q matrix
.. autofunction:: potrf           - Cholesky decomposition
.. autofunction:: potri           - Inverse of a positive semidefinite matrix with Cholesky
.. autofunction:: potrs           - Solve linear equation with positive semidefinite
.. autofunction:: pstrf           - Cholesky decomposition of a positive semidefinite matrix
.. autofunction:: qr              - QR decomposition
.. autofunction:: svd             - SVD decomposition
.. autofunction:: symeig          - Eigenvalues and eigenvectors
.. autofunction:: trtrs           - Solves a system of equations with a triangular coefficient
```